### ISSUE TITLE
Design a Dice rolling simulation game

### ISSUE THREAD

**Issue by labesoft** [labesoft/top-projects#18]
We need to design the base concept of the game ahead of the implementation which will ease and accelerate the whole project. This is the start of the 3rd subproject of #1

- [x] wireframe the initial display (dice and table) #24
- [x] minimal storyboard for the gameplay (dice animation: mix, drop, result) #25
- [ ] create the required assets #23

**Comment by benlapETS** [comment]
So far I desinged some assets like Dice, Card, Craps table, rendered images and rendered 3D animation with [Blender](www.blender.org) in an effort to find the best 3D tools to design our game.

**Comment by benlapETS** [comment]
I think there is more to carry here than we thought at first to prepare the a first iteration. Here is a list of todos:

- wireframe the initial display (dice and table) and the gameplay (dice animation: mix, drop, result)
- create the required assets
- convert our blender assets to panda 3D models, more exactly [bam files](https://docs.panda3d.org/1.10/python/tools/model-export/converting-from-blender) 
-
